"""
Script to update tour stop translations in MongoDB
"""
import os
from dotenv import load_dotenv
from pymongo import MongoClient

load_dotenv()

MONGO_URL = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
DB_NAME = os.environ.get('DB_NAME', 'spis_castle_paid')

client = MongoClient(MONGO_URL)
db = client[DB_NAME]

TRANSLATIONS = {
    1: {
        "en": {"title": "Welcome to Spiš Castle", "short_description": "Main entrance and introduction to the castle complex", "description": "Welcome to one of the largest castle complexes in Europe. Welcome to the largest monument with its exceptional architecture, which is an example of the construction development of the castle in different stylistic periods. Welcome to Spiš Castle, which has undergone a gradual transformation from a royal castle, through a noble residence, to a military fortress. Please move further into the middle of this courtyard to the tents, where on the right, under the wall, there is a photograph of the entire castle complex from a height. Please be careful under your feet because there are stones sticking out and it is slippery on the sidewalk as well as inside the tower."},
        "sk": {"title": "Vitajte na Spišskom hrade", "short_description": "Hlavný vstup a úvod do hradného komplexu", "description": "Vitajte v jednom z najväčších hradných komplexov v Európe. Vitajte v najväčšej pamiatke s výnimočnou architektúrou, ktorá je príkladom stavebného vývoja hradu v rôznych slohových obdobiach. Vitajte na Spišskom hrade, ktorý prešiel postupnou premenou z kráľovského hradu cez šľachtické sídlo až na vojenskú pevnosť. Prosím, posuňte sa ďalej do stredu tohto nádvoria k stanom, kde vpravo pod múrom je fotografia celého hradného komplexu z výšky. Prosím, dávajte pozor pod nohami, pretože vystupujú kamene a na chodníku je klzko, rovnako ako vo vnútri veže."},
        "de": {"title": "Willkommen auf Burg Spiš", "short_description": "Haupteingang und Einführung in den Burgkomplex", "description": "Willkommen in einem der größten Burgkomplexe Europas. Die Zipser Burg hat eine schrittweise Verwandlung von einer königlichen Burg über eine Adelsresidenz zu einer Militärfestung durchlaufen. Bitte bewegen Sie sich weiter in die Mitte dieses Hofes zu den Zelten, wo sich rechts unter der Mauer eine Fotografie des gesamten Burgkomplexes aus der Höhe befindet. Bitte achten Sie auf Ihren Weg, da Steine herausragen und der Gehweg sowie das Innere des Turms rutschig sind."},
        "pl": {"title": "Witamy na Zamku Spiskim", "short_description": "Główne wejście i wprowadzenie do kompleksu zamkowego", "description": "Witamy w jednym z największych kompleksów zamkowych w Europie. Zamek Spiski przeszedł stopniową przemianę z zamku królewskiego, przez szlachecką rezydencję, do wojskowej twierdzy. Proszę przejść dalej na środek tego dziedzińca do namiotów, gdzie po prawej stronie, pod murem, znajduje się fotografia całego kompleksu zamkowego z wysokości. Proszę uważać na nogi, ponieważ wystają kamienie i jest ślisko."},
        "hu": {"title": "Üdvözöljük a Szepesi várban", "short_description": "Főbejárat és bevezetés a várkomplexumba", "description": "Üdvözöljük Európa egyik legnagyobb várkomplexumában. A Szepesi vár fokozatosan alakult át királyi várból nemesi rezidencián át katonai erőddé. Kérem, menjenek tovább az udvar közepére a sátrakhoz, ahol jobbra, a fal alatt, egy fénykép látható az egész várkomplexumról magasból. Kérem, vigyázzanak a lábukra, mert kövek állnak ki és csúszós a járda."},
        "fr": {"title": "Bienvenue au Château de Spiš", "short_description": "Entrée principale et introduction au complexe du château", "description": "Bienvenue dans l'un des plus grands complexes de châteaux d'Europe. Le Château de Spiš a subi une transformation progressive d'un château royal, en passant par une résidence noble, pour devenir une forteresse militaire. Veuillez vous déplacer au milieu de cette cour vers les tentes, où à droite, sous le mur, se trouve une photographie de l'ensemble du complexe depuis les hauteurs."},
        "es": {"title": "Bienvenido al Castillo de Spiš", "short_description": "Entrada principal e introducción al complejo del castillo", "description": "Bienvenido a uno de los complejos de castillos más grandes de Europa. El Castillo de Spiš ha experimentado una transformación gradual desde un castillo real, a través de una residencia noble, hasta una fortaleza militar. Por favor, avance hacia el centro de este patio hacia las tiendas, donde a la derecha, bajo la pared, hay una fotografía de todo el complejo desde las alturas."},
        "ru": {"title": "Добро пожаловать в Спишский Град", "short_description": "Главный вход и знакомство с замковым комплексом", "description": "Добро пожаловать в один из крупнейших замковых комплексов Европы. Спишский Град претерпел постепенное преобразование от королевского замка через дворянскую резиденцию до военной крепости. Пожалуйста, пройдите вглубь этого двора к палаткам, где справа, у стены, находится фотография всего замкового комплекса с высоты."},
        "zh": {"title": "欢迎来到斯皮什城堡", "short_description": "主入口及城堡建筑群介绍", "description": "欢迎来到欧洲最大的城堡建筑群之一。斯皮什城堡经历了从皇家城堡、贵族府邸到军事要塞的逐步转变。请走到这个庭院中间的帐篷处，在右侧墙壁下有一张整个城堡建筑群的高空照片。请注意脚下，人行道和塔楼内部都很滑。"},
    },
    2: {
        "en": {"title": "In Front of the Castle Photograph", "short_description": "Prehistoric settlement and the beginnings of the castle", "description": "The castle hill was already inhabited in prehistoric times and the Neolithic period. The finds confirm the rich settlement by the Celtic tribes trading in volcanic glass and obsidian. They were excellent potters and craftsmen. The hillfort on Spišský vrch has served as the administrative and economic center of this region since time immemorial. The story of the royal castle began during the reign of King Bela III at the end of the 12th century with the construction of a large residential observation tower Donžon on top of a rocky outcrop. In 1221, the castle became the seat of Koloman of Galicia from the royal Árpád dynasty and slowly began to turn into a residence."},
        "sk": {"title": "Pred fotografiou hradu", "short_description": "Prehistorické osídlenie a počiatky hradu", "description": "Hradný kopec bol obývaný už v prehistorických dobách a neolite. Nálezy potvrdzujú bohaté osídlenie keltskými kmeňmi obchodujúcimi so sopečným sklom a obsidiánom. Boli vynikajúcimi hrnčiarmi a remeselníkmi. Hradisko na Spišskom vrchu slúžilo ako administratívne a hospodárske centrum tohto regiónu od nepamäti. Príbeh kráľovského hradu sa začal za vlády kráľa Bela III. na konci 12. storočia výstavbou veľkej obytnej pozorovacej veže Donžon na vrchole skalného výbežku. V roku 1221 sa hrad stal sídlom Kolomana Haličského z kráľovskej dynastie Arpádovcov."},
        "de": {"title": "Vor der Burgfotografie", "short_description": "Prähistorische Besiedlung und die Anfänge der Burg", "description": "Der Burghügel war bereits in der Vorgeschichte bewohnt. Die Funde bestätigen die reiche Besiedlung durch keltische Stämme, die mit Vulkanglas und Obsidian handelten. Die Geschichte der königlichen Burg begann während der Herrschaft von König Béla III. am Ende des 12. Jahrhunderts mit dem Bau eines Beobachtungsturms Donžon auf einem Felsvorsprung. Im Jahr 1221 wurde die Burg Sitz von Koloman von Galizien aus der Árpáden-Dynastie."},
        "pl": {"title": "Przed fotografią zamku", "short_description": "Prehistoryczne osadnictwo i początki zamku", "description": "Wzgórze zamkowe było zamieszkane już w czasach prehistorycznych. Znaleziska potwierdzają bogate osadnictwo przez plemiona celtyckie handlujące szkłem wulkanicznym i obsydianem. Historia zamku królewskiego rozpoczęła się za panowania króla Béli III pod koniec XII wieku budową wieży obserwacyjnej Donžon na szczycie skalnego wystąpu. W 1221 roku zamek stał się siedzibą Kolomana Halickiego z dynastii Arpadów."},
        "hu": {"title": "A várkép előtt", "short_description": "Őskori település és a vár kezdetei", "description": "A várdomb már az őskorban is lakott volt. A leletek megerősítik a kelta törzsek gazdag letelepedését, akik vulkáni üveggel és obszidiánnal kereskedtek. A királyi vár története III. Béla király uralma idején kezdődött a 12. század végén egy Donžon torony építésével egy sziklakiugrón. 1221-ben a vár Galíciai Kálmán székhelye lett az Árpád-dinasztiából."},
        "fr": {"title": "Devant la photographie du château", "short_description": "Peuplement préhistorique et débuts du château", "description": "La colline du château était déjà habitée à l'époque préhistorique. Les trouvailles confirment le riche peuplement par les tribus celtes commerçant avec du verre volcanique et de l'obsidienne. L'histoire du château royal a commencé sous le règne du roi Béla III à la fin du XIIe siècle avec la construction d'une tour d'observation Donžon. En 1221, le château est devenu le siège de Koloman de Galice de la dynastie Árpád."},
        "es": {"title": "Frente a la fotografía del castillo", "short_description": "Asentamiento prehistórico y los comienzos del castillo", "description": "La colina del castillo ya estaba habitada en tiempos prehistóricos. Los hallazgos confirman el rico asentamiento por las tribus celtas que comerciaban con vidrio volcánico y obsidiana. La historia del castillo real comenzó durante el reinado del rey Béla III a finales del siglo XII con la construcción de la torre Donžon. En 1221, el castillo se convirtió en la sede de Koloman de Galicia de la dinastía Árpád."},
        "ru": {"title": "Перед фотографией замка", "short_description": "Доисторическое поселение и истоки замка", "description": "Замковая гора была заселена ещё в доисторические времена. Находки подтверждают богатое заселение кельтскими племенами, торговавшими вулканическим стеклом и обсидианом. История королевского замка началась в правление короля Белы III в конце XII века со строительства наблюдательной башни Донжон на скалистом выступе. В 1221 году замок стал резиденцией Коломана Галицкого из династии Арпадов."},
        "zh": {"title": "城堡照片前", "short_description": "史前定居点和城堡的起源", "description": "城堡山在史前时代就已有人居住。发现物证实了凯尔特部落的丰富定居，他们交易火山玻璃和黑曜石。城堡历史始于贝拉三世国王统治时期，12世纪末在岩石露头顶部建造了观察塔东荣。1221年，城堡成为阿尔帕德王朝加利西亚科洛曼的驻地。"},
    },
    3: {
        "en": {"title": "At the Castle Model", "short_description": "History of the castle complex and the Csáky family", "description": "In this room you can see sketches showing that the story of Spiš Castle began with the construction of a single defensive tower and ended as shown in the Model of Spiš Castle — the final state at the beginning of the 18th century when it was still inhabited. The model of 132 rooms was created by Adolph Stephanie. At the beginning of the 18th century the castle ceased to be a comfortable manor house. Štefan Csáky had 26 children with 2 women and the family left the castle. The great fire broke out in 1870 — historians talk about three theories including arson by the Csáky family to avoid roof taxes. After World War II in 1945 the castle was nationalized and in 1961 declared a national cultural monument."},
        "sk": {"title": "Pri modeli hradu", "short_description": "História hradného komplexu a rodiny Csákyovcov", "description": "V tejto miestnosti môžete vidieť náčrty kresieb, ktoré ukazujú, že príbeh Spišského hradu začal výstavbou jednej obrannej veže a skončil tak, ako je znázornené na modeli Spišského hradu — konečný stav na začiatku 18. storočia, keď bol ešte obývaný. Model so 132 izbami vytvoril Adolph Stephanie. Na začiatku 18. storočia hrad prestal byť pohodlným sídlom. Štefan Csáky mal 26 detí s 2 ženami a rodina hrad opustila. Veľký požiar vypukol v roku 1870 — historici hovoria o troch teóriách vrátane podpálenia rodinou Csáky kvôli dani zo striech. Po 2. svetovej vojne bol hrad zoštátnený a v roku 1961 vyhlásený za národnú kultúrnu pamiatku."},
        "de": {"title": "Am Burgmodell", "short_description": "Geschichte des Burgkomplexes und der Familie Csáky", "description": "In diesem Raum sehen Sie Skizzen, die die Geschichte der Zipser Burg zeigen — von einem einzelnen Turm bis zum Modell mit 132 Zimmern von Adolph Stephanie. Zu Beginn des 18. Jahrhunderts hörte die Burg auf, ein komfortables Herrenhaus zu sein. Štefan Csáky hatte 26 Kinder mit 2 Frauen und die Familie verließ die Burg. Der Brand von 1870 bleibt ungeklärt. Nach dem Zweiten Weltkrieg wurde die Burg verstaatlicht und 1961 zum nationalen Kulturdenkmal erklärt."},
        "pl": {"title": "Przy modelu zamku", "short_description": "Historia kompleksu zamkowego i rodziny Csáky", "description": "W tym pokoju można zobaczyć szkice pokazujące historię Zamku Spiskiego — od pojedynczej wieży do modelu ze 132 pokojami autorstwa Adolpha Stephanie. Na początku XVIII wieku zamek przestał być wygodną rezydencją. Štefan Csáky miał 26 dzieci z 2 kobietami i rodzina opuściła zamek. Wielki pożar z 1870 roku — trzy teorie. Po II wojnie światowej zamek został upaństwowiony i w 1961 roku uznany za narodowy zabytek kultury."},
        "hu": {"title": "A vármodellnél", "short_description": "A várkomplexum és a Csáky család története", "description": "Ebben a szobában vázlatrajzokat láthat a Szepesi vár történetéről — egyetlen toronytól az Adolph Stephanie által készített 132 szobás modelig. A 18. század elejére a vár elvesztette kényelmes kastélyjellegét. Štefan Csákynak 26 gyermeke volt 2 nőtől és a család elhagyta a várat. Az 1870-es tűz oka ismeretlen — három elmélet. A II. világháború után a várat államosították és 1961-ben nemzeti kulturális emlékké nyilvánították."},
        "fr": {"title": "Au modèle du château", "short_description": "Histoire du complexe du château et de la famille Csáky", "description": "Dans cette salle, vous voyez des esquisses de l'histoire du château — d'une seule tour au modèle de 132 pièces créé par Adolph Stephanie. Au début du XVIIIe siècle, le château a cessé d'être une demeure confortable. Štefan Csáky avait 26 enfants avec 2 femmes et la famille a quitté le château. L'incendie de 1870 reste inexpliqué. Après la Seconde Guerre mondiale, le château a été nationalisé et déclaré monument en 1961."},
        "es": {"title": "En el modelo del castillo", "short_description": "Historia del complejo del castillo y la familia Csáky", "description": "En esta sala puede ver bocetos de la historia del castillo — desde una sola torre hasta el modelo de 132 habitaciones de Adolph Stephanie. A principios del siglo XVIII el castillo dejó de ser una mansión cómoda. Štefan Csáky tuvo 26 hijos con 2 mujeres y la familia abandonó el castillo. El incendio de 1870 sin explicación. Después de la Segunda Guerra Mundial el castillo fue nacionalizado y declarado monumento en 1961."},
        "ru": {"title": "У модели замка", "short_description": "История замкового комплекса и семьи Чаки", "description": "В этом зале можно увидеть эскизы истории замка — от единственной башни до модели с 132 комнатами Адольфа Штефани. В начале XVIII века замок перестал быть удобной усадьбой. У Штефана Чаки было 26 детей от 2 жён и семья покинула замок. Причина пожара 1870 года — три теории. После Второй мировой войны замок был национализирован и в 1961 году объявлен национальным памятником."},
        "zh": {"title": "在城堡模型前", "short_description": "城堡建筑群历史和查基家族", "description": "在这个房间里，您可以看到城堡历史的素描——从单一塔楼到阿道夫·斯蒂芬尼创建的132个房间的模型。18世纪初，城堡不再是舒适的庄园。什特凡·查基与两名女性育有26个孩子，家族离开了城堡。1870年大火——三种理论。二战后城堡被国有化，1961年被宣布为国家文化古迹。"},
    },
    4: {
        "en": {"title": "In the Kitchen", "short_description": "Medieval cuisine and life in the castle", "description": "The basic component of the diet was meat — poultry, beef, pork or game. The nobility could always afford fresh meat, while commoners preferred pork. The most common preservation methods were smoking, salting and drying. Among popular delicacies were cereal porridges prepared in dozens of ways. A recipe from the 16th century for the four-colored porridge has survived to this day. Hungarian cuisine in the Middle Ages was known throughout Europe as very spicy. At certain times during pandemics, all adults and children drank wine and beer instead of water. When the lord wanted to impress guests, several courses were served and the table was decorated with a peacock."},
        "sk": {"title": "V kuchyni", "short_description": "Stredoveká kuchyňa a život na hrade", "description": "Základnou zložkou stravy bolo mäso — hydina, hovädzie, bravčové alebo zverina. Šľachta si vždy mohla dovoliť čerstvé mäso, kým ľudia z nižších vrstiev preferovali bravčové. Najčastejším spôsobom konzervovania bolo údenie, solenie a sušenie. Medzi obľúbené pochúťky patrili obilné kaše pripravované desiatkymi spôsobmi. Recept zo 16. storočia na štvorfarebnú kašu sa zachoval dodnes. Uhorská kuchyňa bola v celej Európe známa ako veľmi korenená. V čase pandémií pili všetci víno a pivo namiesto vody. Keď chcel pán hradu zaujať hostí, podávalo sa viacero chodov a stôl zdobil páv."},
        "de": {"title": "In der Küche", "short_description": "Mittelalterliche Küche und das Leben auf der Burg", "description": "Der Grundbestandteil der Ernährung war Fleisch — Geflügel, Rind, Schwein oder Wild. Der Adel konnte sich stets frisches Fleisch leisten, während einfache Leute Schweinefleisch bevorzugten. Die häufigsten Konservierungsmethoden waren Räuchern, Salzen und Trocknen. Beliebt waren Getreidebrei auf Dutzende Arten. In Zeiten von Pandemien tranken alle Wein und Bier statt Wasser."},
        "pl": {"title": "W kuchni", "short_description": "Średniowieczna kuchnia i życie na zamku", "description": "Podstawowym składnikiem diety było mięso — drób, wołowina, wieprzowina lub dziczyzna. Szlachta mogła sobie pozwolić na świeże mięso, zwykli ludzie preferowali wieprzowinę. Najpopularniejsze metody konserwowania to wędzenie, solenie i suszenie. Popularne były kasze zbożowe na dziesiątki sposobów. W czasie pandemii wszyscy pili wino i piwo zamiast wody."},
        "hu": {"title": "A konyhában", "short_description": "Középkori konyha és élet a várban", "description": "Az étrend alapvető összetevője a hús volt — baromfi, marha, sertés vagy vad. A nemesség mindig megengedhette magának a friss húst, míg a köznép a sertéshúst részesítette előnyben. A legnépszerűbb tartósítási módok a füstölés, sózás és szárítás. Járványok idején mindenki bort és sört ivott víz helyett."},
        "fr": {"title": "Dans la cuisine", "short_description": "Cuisine médiévale et vie au château", "description": "La composante de base de l'alimentation était la viande — volaille, bœuf, porc ou gibier. La noblesse pouvait toujours se permettre de la viande fraîche. Les méthodes de conservation les plus courantes étaient le fumage, le salage et le séchage. Les bouillies de céréales préparées de dizaines de façons étaient populaires. En temps de pandémies, tous buvaient du vin et de la bière au lieu de l'eau."},
        "es": {"title": "En la cocina", "short_description": "Cocina medieval y vida en el castillo", "description": "El componente básico de la dieta era la carne — aves, ternera, cerdo o caza. La nobleza siempre podía permitirse carne fresca. Los métodos de conservación más comunes eran el ahumado, la salazón y el secado. Eran populares las papillas de cereales de docenas de maneras. En tiempo de pandemias todos bebían vino y cerveza en lugar de agua."},
        "ru": {"title": "На кухне", "short_description": "Средневековая кухня и жизнь в замке", "description": "Основным компонентом питания было мясо — птица, говядина, свинина или дичь. Знать всегда могла позволить себе свежее мясо. Наиболее распространёнными способами сохранения были копчение, соление и сушка. Популярными были зерновые каши десятками способов. Во время пандемий все пили вино и пиво вместо воды."},
        "zh": {"title": "在厨房", "short_description": "中世纪烹饪和城堡生活", "description": "饮食的基本成分是肉类——家禽、牛肉、猪肉或野味。贵族总能负担得起新鲜肉类，平民更喜欢猪肉。最常见的保存方式是熏制、腌制和干燥。各种方式制作的谷物粥非常受欢迎。在瘟疫期间，所有人都喝葡萄酒和啤酒而不是水。"},
    },
    5: {
        "en": {"title": "On the Lower Terrace", "short_description": "UNESCO World Heritage Site and surroundings", "description": "On the walls we can see photographs expressing why this entire area was inscribed on the UNESCO World Cultural and Natural Heritage List in 1993, along with the early Gothic church of the Holy Spirit in Žehra. Spiš Castle forms the center of this unique area and for many years was the center of secular power in Spiš. In 2009, Levoča was also added to the list, where you can admire the magnificent altar by Master Pavol and the beautiful sculptures in the church of St. James. Mostly everything from the photographs can be seen from this terrace in person."},
        "sk": {"title": "Na dolnej terase", "short_description": "Lokalita svetového dedičstva UNESCO a okolie", "description": "Na stenách môžeme vidieť fotografie vyjadrujúce dôvody, prečo bola celá táto oblasť zapísaná na Zoznam svetového kultúrneho a prírodného dedičstva UNESCO v roku 1993, spolu s ranostredovekou gotickou Kostolíkom sv. Ducha v Žehre. Spišský hrad tvorí centrum tejto jedinečnej oblasti a po mnoho rokov bol centrom svetskej moci na Spiši. V roku 2009 bola do zoznamu pridaná aj Levoča, kde možno obdivovať nádherný oltár Majstra Pavla a krásne sochy v Kostole sv. Jakuba. Z tejto terasy možno vidieť väčšinu toho, čo je na fotografiách."},
        "de": {"title": "Auf der unteren Terrasse", "short_description": "UNESCO-Weltkulturerbe und Umgebung", "description": "An den Wänden sehen wir Fotografien, die zeigen, warum dieses Gebiet 1993 in die UNESCO-Liste aufgenommen wurde, zusammen mit der frühgotischen Kirche des Heiligen Geistes in Žehra. Die Zipser Burg bildet das Zentrum dieses einzigartigen Gebiets. Im Jahr 2009 wurde auch Levoča zur Liste hinzugefügt, wo man den prächtigen Altar von Meister Pavol und die Skulpturen in der Kirche St. Jakobus bewundern kann."},
        "pl": {"title": "Na dolnym tarasie", "short_description": "Obiekt Światowego Dziedzictwa UNESCO i okolice", "description": "Na ścianach możemy zobaczyć fotografie pokazujące, dlaczego cały ten obszar został wpisany na Listę UNESCO w 1993 roku, wraz z wczesnogotyckim kościołem Ducha Świętego w Žehrze. Zamek Spiski stanowi centrum tego wyjątkowego obszaru. W 2009 roku do listy dodano również Lewoczę, gdzie można podziwiać ołtarz Mistrza Pawła i rzeźby w kościele św. Jakuba."},
        "hu": {"title": "Az alsó teraszon", "short_description": "UNESCO Világörökség és környéke", "description": "A falakon fényképeket láthatunk, amelyek kifejezik, miért vette fel az UNESCO 1993-ban ezt az egész területet a listájára, a Žehrai Szentlélek-templommal együtt. A Szepesi vár ennek az egyedülálló területnek a középpontja. 2009-ben Lőcsét is felvették a listára, ahol megcsodálhatja Pavol mester oltárát és a Szent Jakab-templomban lévő szobrokat."},
        "fr": {"title": "Sur la terrasse inférieure", "short_description": "Site du patrimoine mondial de l'UNESCO et environs", "description": "Sur les murs, nous voyons des photographies expliquant pourquoi cette zone a été inscrite sur la liste de l'UNESCO en 1993, avec l'église gothique primitive du Saint-Esprit à Žehra. Le château de Spiš forme le centre de cette zone unique. En 2009, Levoča a également été ajoutée, où vous pouvez admirer l'autel du Maître Pavol et les sculptures dans l'église Saint-Jacques."},
        "es": {"title": "En la terraza inferior", "short_description": "Patrimonio Mundial de la UNESCO y alrededores", "description": "En las paredes vemos fotografías que explican por qué esta área fue inscrita en la lista de la UNESCO en 1993, junto con la iglesia gótica del Espíritu Santo en Žehra. El Castillo de Spiš forma el centro de esta área única. En 2009, Levoča también fue añadida, donde puede admirar el altar del Maestro Pavol y las esculturas en la iglesia de San Santiago."},
        "ru": {"title": "На нижней террасе", "short_description": "Объект Всемирного наследия ЮНЕСКО и окрестности", "description": "На стенах мы видим фотографии, объясняющие, почему вся эта территория была внесена в список ЮНЕСКО в 1993 году, вместе с раннеготической церковью Святого Духа в Жехре. Спишский Град является центром этой уникальной территории. В 2009 году в список была добавлена также Левоча, где можно полюбоваться алтарём Мастера Павла и скульптурами в церкви Святого Якова."},
        "zh": {"title": "在下层露台", "short_description": "联合国教科文组织世界遗产地及周边环境", "description": "在墙壁上，我们可以看到照片，说明为什么整个地区在1993年被列入联合国教科文组织世界遗产名录，连同热赫拉的早期哥特式圣灵教堂。斯皮什城堡是这个独特地区的中心。2009年，莱沃恰也被加入名单，在那里您可以欣赏帕沃尔大师的祭坛和圣雅各教堂内的雕塑。"},
    },
    6: {
        "en": {"title": "On the Romanesque Forecourt", "short_description": "The oldest part of the castle and the Tatar invasion legend", "description": "You have entered through the oldest Romanesque gate, standing at a place associated with the invasion of the Tatars and the first written record of the castle from 1249. This part of the castle was built after 1241 when the Mongols invaded Hungary and plundered the entire surrounding countryside. The enemies did not conquer Spiš Castle, probably because it was made of stone. The situation changed when Matthias Corvinus donated the castle to the Zápoľský family, who modernized it in the spirit of late Gothic. Listen to the legend of the Tatar princess Šad — a story of love between a castle defender and a Tatar princess during the siege of 1241."},
        "sk": {"title": "Na románskom predhradí", "short_description": "Najstaršia časť hradu a legenda o tatárskom vpáde", "description": "Vstúpili ste cez najstaršiu románsku bránu a stojíte na mieste spojenom s vpádom Tatárov a prvou písomnou zmienkou o hrade z roku 1249. Táto časť hradu bola postavená po roku 1241, keď Mongoli vtrhli do Uhorska a vyplienili celé okolie. Nepriatelia Spišský hrad nedobyli, pravdepodobne preto, že bol postavený z kameňa. Situácia sa zmenila, keď Matej Korvín daroval hrad rodine Zápoľskovcov, ktorí ho modernizovali v duchu neskorej gotiky. Vypočujte si legendu o tatárskej princeznej Šad — príbeh lásky medzi obrancom hradu a tatárskou princeznou počas obliehania v roku 1241."},
        "de": {"title": "Auf dem romanischen Vorhof", "short_description": "Der älteste Teil der Burg und die Legende vom Tatarensturm", "description": "Sie haben das älteste romanische Tor betreten, einen Ort der mit dem Tatarensturm und der ersten schriftlichen Erwähnung der Burg von 1249 verbunden ist. Dieser Teil wurde nach 1241 erbaut, als die Mongolen Ungarn überfielen. Die Feinde haben die Burg nicht erobert, weil sie aus Stein gebaut war. Matthias Corvinus schenkte die Burg später der Familie Zápoľský. Hören Sie sich die Legende der tatarischen Prinzessin Šad an."},
        "pl": {"title": "Na romańskim przedzamczu", "short_description": "Najstarsza część zamku i legenda o najeździe tatarskim", "description": "Weszliście przez najstarszą romańską bramę, w miejscu związanym z najazdem Tatarów i pierwszą pisemną wzmianką o zamku z 1249 roku. Ta część powstała po 1241 roku, gdy Mongołowie najechali Węgry. Wrogom nie udało się zdobyć zamku. Maciej Korwin podarował później zamek rodzinie Zápoľskich. Posłuchajcie legendy o tatarskiej księżniczce Šad."},
        "hu": {"title": "A román előudvaron", "short_description": "A vár legrégebbi része és a tatár betörés legendája", "description": "A legrégebbi román kapun lépett be, egy helyen, amely a tatárok betöréséhez és a vár 1249-es első írásos emlékéhez kapcsolódik. Ez a rész 1241 után épült, amikor a mongolok megtámadták Magyarországot. Az ellenségeknek nem sikerült elfoglalni a várat. Mátyás Corvinus később a Zápoľský családnak adományozta. Hallgassák meg Šad tatár hercegnő legendáját."},
        "fr": {"title": "Sur la cour romane", "short_description": "La partie la plus ancienne du château et la légende de l'invasion tatare", "description": "Vous avez franchi la plus ancienne porte romane, associée à l'invasion tatare et à la première mention écrite du château de 1249. Cette partie fut construite après 1241, quand les Mongols envahirent la Hongrie. Les ennemis n'ont pas conquis le château. Matthias Corvin a ensuite donné le château à la famille Zápoľský. Écoutez la légende de la princesse tatare Šad."},
        "es": {"title": "En el patio románico", "short_description": "La parte más antigua del castillo y la leyenda de la invasión tártara", "description": "Ha entrado por la puerta románica más antigua, asociada con la invasión tártara y la primera mención escrita del castillo de 1249. Esta parte fue construida después de 1241, cuando los mongoles invadieron Hungría. Los enemigos no pudieron conquistar el castillo. Matthias Corvino donó el castillo a la familia Zápoľský. Escuche la leyenda de la princesa tártara Šad."},
        "ru": {"title": "На романском предворье", "short_description": "Старейшая часть замка и легенда о татарском нашествии", "description": "Вы вошли через старейшие романские ворота, место, связанное с татарским нашествием и первым письменным упоминанием о замке 1249 года. Эта часть была построена после 1241 года, когда монголы вторглись в Венгрию. Врагам не удалось завоевать замок. Матиас Корвин впоследствии подарил замок семье Запольских. Послушайте легенду о татарской принцессе Шад."},
        "zh": {"title": "在罗马式前院", "short_description": "城堡最古老的部分和鞑靼入侵传说", "description": "您穿过最古老的罗马式大门，站在一个与鞑靼入侵和1249年城堡第一次书面记录相关的地方。这部分建于1241年之后，当时蒙古人入侵匈牙利。敌人没能攻占城堡。马提亚斯·科维努斯后来将城堡赠给扎波尔斯基家族。聆听鞑靼公主沙德的传说。"},
    },
    7: {
        "en": {"title": "On the Upper Terrace", "short_description": "Panoramic view of Spiš region and the Tatras", "description": "Spiš Castle stands on top of a travertine rock at an altitude of 634 m above sea level. The almost perpendicular walls of the hill made this place one of the best protected castles in the country. In the past, two important trade routes ran under the castle hill — one connected southern Europe with Poland and the Baltic Sea, the second connected Slovakia from west to east. From this lookout you can see almost half of the Slovak mountains: the Branisko Mountains, the Low Tatras, Kriváň Peak, the High Tatras and the Levoča Mountains. You can also see the twin-towered Cathedral of St. Martin in Spišská Kapitula and the Dreveník hill to the left."},
        "sk": {"title": "Na hornej terase", "short_description": "Panoramatický výhľad na región Spiš a Tatry", "description": "Spišský hrad stojí na vrchole travertínovej skaly v nadmorskej výške 634 m nad morom. Takmer kolmé steny kopca robili z tohto miesta jeden z najlepšie chránených hradov v krajine. V minulosti pod hradným kopcom viedli dve dôležité obchodné cesty — jedna spájala južnú Európu s Poľskom a Baltom, druhá Slovensko od západu na východ. Z tejto vyhliadky môžete vidieť takmer polovicu slovenských hôr: Branisko, Nízke Tatry, Kriváň, Vysoké Tatry a Levočské vrchy. Vidíte tiež dvojvežovú Katedrálu sv. Martina na Spišskej Kapitule a Dreveník naľavo."},
        "de": {"title": "Auf der oberen Terrasse", "short_description": "Panoramablick auf die Zips-Region und die Tatra", "description": "Die Zipser Burg steht auf einem Travertinfelsen in 634 m Höhe. Die fast senkrechten Felswände machten diesen Ort zu einer der am besten geschützten Burgen. In der Vergangenheit verliefen zwei wichtige Handelswege unter der Burg. Von diesem Aussichtspunkt sehen Sie fast die Hälfte der slowakischen Berge: Branisko, Niedere Tatra, Kriváň, Hohe Tatra und Levoča-Gebirge. Sie sehen auch die zweitürmige Kathedrale St. Martin in Spišská Kapitula."},
        "pl": {"title": "Na górnym tarasie", "short_description": "Panoramiczny widok na region Spiszu i Tatry", "description": "Zamek Spiski stoi na szczycie trawertynowej skały na wysokości 634 m n.p.m. Niemal pionowe mury wzgórza czyniły to miejsce jednym z najlepiej chronionych zamków. W przeszłości pod wzgórzem przebiegały dwa ważne szlaki handlowe. Z tego punktu widokowego widać prawie połowę słowackich gór: Branisko, Niżne Tatry, Krywań, Tatry Wysokie i Góry Lewockie. Widać również dwuwieżową katedrę św. Marcina w Spišskiej Kapitule."},
        "hu": {"title": "A felső teraszon", "short_description": "Panorámás kilátás a Szepességre és a Tátrára", "description": "A Szepesi vár egy travertinszikla tetején áll 634 méter magasságban. A domb szinte merőleges falai az ország egyik legjobban védett várává tették. A múltban két fontos kereskedelmi útvonal futott alatta. Erről a kilátóról a szlovák hegység majdnem felét láthatja: Branisko, Alacsony-Tátra, Kriváň, Magas-Tátra és Lőcsei-hegység. Látható a kéttornyú Szent Márton székesegyház a Szepeshelyen is."},
        "fr": {"title": "Sur la terrasse supérieure", "short_description": "Vue panoramique sur la région de Spiš et les Tatras", "description": "Le château de Spiš se dresse sur une roche de travertin à 634 m d'altitude. Les murs presque verticaux ont fait de cet endroit l'un des châteaux les mieux protégés. Dans le passé, deux routes commerciales importantes passaient en dessous. De ce belvédère, vous voyez presque la moitié des montagnes slovaques: Branisko, Basses Tatras, Kriváň, Hautes Tatras et monts Levoča. On voit aussi la cathédrale à deux tours de Spišská Kapitula."},
        "es": {"title": "En la terraza superior", "short_description": "Vista panorámica de la región de Spiš y los Tatras", "description": "El Castillo de Spiš se alza sobre una roca de travertino a 634 m. Las murallas casi verticales lo convirtieron en uno de los castillos mejor protegidos. En el pasado, dos rutas comerciales pasaban debajo. Desde este mirador ve casi la mitad de las montañas eslovacas: Branisko, Bajos Tatras, Kriváň, Altos Tatras y montes Levoča. También se ve la catedral de dos torres de Spišská Kapitula."},
        "ru": {"title": "На верхней террасе", "short_description": "Панорамный вид на регион Спиш и Татры", "description": "Спишский Град стоит на травертиновой скале на высоте 634 м. Почти отвесные стены холма делали его одним из самых защищённых замков. В прошлом под горой проходили два торговых пути. С этой смотровой площадки видно почти половину словацких гор: Браниско, Низкие Татры, Кривань, Высокие Татры и горы Левоча. Виден также двухбашенный собор Святого Мартина в Спишской Капитуле."},
        "zh": {"title": "在上层露台", "short_description": "斯皮什地区和塔特拉山的全景", "description": "斯皮什城堡矗立在海拔634米的石灰华岩石顶部。山丘几乎垂直的墙壁使这里成为该国保护最好的城堡之一。过去山下有两条重要的贸易路线经过。从这个瞭望台可以看到几乎一半的斯洛伐克山脉：布拉尼斯科山、低塔特拉山、克里旺峰、高塔特拉山和莱沃恰山。还可以看到斯皮什卡皮图拉双塔圣马丁大教堂。"},
    },
    8: {
        "en": {"title": "Lower Courtyard", "short_description": "The youngest part of the castle built by Jan Jiskra", "description": "From here there is a beautiful view of the entire lower courtyard built in the mid-15th century. In the left corner you can see the stone foundations of a Celtic sanctuary. The creation of the lower courtyard is connected with the Czech nobleman Ján Jiskra of Brandýs, who came here when civil war broke out in Hungary. After acquiring the castle, Jiskra had a military camp built for his soldiers, surrounded by large walls 7 to 9 m high and up to three meters thick. The walls are interrupted by two square defensive watchtowers. In the right tower there is an exhibition of the torture chamber. In the left tower there is information about wild animals such as ground squirrels and the neighboring Dreveník hill."},
        "sk": {"title": "Dolné nádvorie", "short_description": "Najmladšia časť hradu postavená Jánom Jiskrom", "description": "Odtiaľto je krásny výhľad na celé dolné nádvorie postavené v polovici 15. storočia. V ľavom rohu nádvoria možno vidieť kamenné základy pozostatkov keltskej svätyne. Vznik dolného nádvoria sa spája s menom českého šľachtica Jána Jiskru z Brandýsa, ktorý k nám prišiel keď v Uhorsku vypukla občianska vojna. Po získaní hradu dal Jiskra pre svojich vojakov postaviť vojenský tábor obohnaný múrmi vysokými 7 až 9 m a hrubými až tri metre. Mohutné múry sú prerušené dvoma štvorcovými obrannými strážnymi vežami. Vo veži vpravo sa nachádza expozícia mučiarne. V ľavej veži sú informácie o divých zvieratách, ako sú sysle, a o susednom kopci Dreveník."},
        "de": {"title": "Unterer Burghof", "short_description": "Der jüngste Teil der Burg, erbaut von Jan Jiskra", "description": "Von hier aus hat man einen schönen Blick auf den gesamten unteren Burghof aus der Mitte des 15. Jahrhunderts. In der linken Ecke sieht man Steinfundamente eines keltischen Heiligtums. Der Hof ist mit Ján Jiskra von Brandýs verbunden, der in Zeiten des Bürgerkriegs in Ungarn hierher kam. Jiskra ließ einen Militärlager bauen, mit Mauern 7-9 m hoch und bis zu drei Meter dick. Im rechten Turm gibt es die Folterkammerausstellung, im linken Informationen über Wildtiere und den Dreveník-Hügel."},
        "pl": {"title": "Dolny dziedziniec", "short_description": "Najmłodsza część zamku zbudowana przez Jana Jiskrę", "description": "Stąd roztacza się piękny widok na cały dolny dziedziniec z połowy XV wieku. W lewym rogu widać kamienne fundamenty celtyckiej świątyni. Dziedziniec wiąże się z Jánem Jiskrą z Brandýs, który przybył tu podczas wojny domowej na Węgrzech. Jiskra zbudował obóz wojskowy z murami 7-9 m wysokimi i do trzech metrów grubymi. W prawej wieży jest ekspozycja izby tortur, w lewej informacje o dzikich zwierzętach i wzgórzu Dreveník."},
        "hu": {"title": "Alsó udvar", "short_description": "A vár legfiatalabb része, amelyet Jan Jiskra épített", "description": "Innen gyönyörű kilátás nyílik a 15. század közepén épült alsó udvarra. A bal sarokban kelta szentély kőalapjai láthatók. Az udvart Ján Jiskra cseh nemes nevéhez fűzik, aki magyarországi polgárháború idején érkezett. Jiskra 7-9 méter magas és három méter vastag falakkal övezett katonai tábort épített. A jobb toronyban kínzókamra-kiállítás, a balban vadállat- és Dreveník-domb információk láthatók."},
        "fr": {"title": "Cour inférieure", "short_description": "La partie la plus récente du château construite par Jan Jiskra", "description": "De là, belle vue sur la cour inférieure du milieu du XVe siècle. Dans le coin gauche, des fondations d'un sanctuaire celte. La cour est liée à Ján Jiskra de Brandýs, venu lors de la guerre civile en Hongrie. Jiskra fit construire un camp militaire avec des murs de 7-9 m de haut et jusqu'à trois mètres d'épaisseur. Dans la tour droite, l'exposition de la chambre de torture; dans la gauche, informations sur la faune et la colline Dreveník."},
        "es": {"title": "Patio inferior", "short_description": "La parte más reciente del castillo construida por Jan Jiskra", "description": "Desde aquí, bella vista del patio inferior de mediados del siglo XV. En la esquina izquierda, cimientos de un santuario celta. El patio está ligado a Ján Jiskra de Brandýs, llegado durante la guerra civil en Hungría. Jiskra construyó un campamento militar con muros de 7-9 m de alto y hasta tres metros de grosor. En la torre derecha, la exposición de la cámara de tortura; en la izquierda, información sobre fauna y la colina Dreveník."},
        "ru": {"title": "Нижний двор", "short_description": "Самая молодая часть замка, построенная Яном Йискрой", "description": "Отсюда красивый вид на нижний двор середины XV века. В левом углу видны каменные фундаменты кельтского святилища. Двор связан с чешским дворянином Яном Йискрой из Брандиса, прибывшим во время гражданской войны в Венгрии. Йискра построил военный лагерь со стенами высотой 7-9 м и толщиной до трёх метров. В правой башне экспозиция пыточной камеры, в левой — информация о дикой природе и холме Древеник."},
        "zh": {"title": "下院", "short_description": "由扬·伊斯克拉建造的城堡最新部分", "description": "从这里可以看到15世纪中期建造的整个下院的美丽景色。左角可以看到凯尔特圣所的石制基础。下院与捷克贵族扬·伊斯克拉·布兰迪斯相连，他在匈牙利内战期间来到这里。伊斯克拉建造了高7至9米、厚达三米的军营围墙。右塔中有酷刑室展览，左塔中有关于野生动物和德列夫尼克山的信息。"},
    },
    9: {
        "en": {"title": "Torture Chamber", "short_description": "Medieval justice and interrogation methods", "description": "The torture chamber was an integral part of the judicial system in the past — a completely normal and legal way to obtain testimony or confession. It was common for a prisoner to be so frightened that they would confess voluntarily just from seeing the instruments. Torture could last for varying lengths and was very effective, almost always resulting in a confession. Not only the torture, but also prison itself was suffering — the dark, cold, damp basement without daylight, prisoner often chained directly to the rock. Torture instruments included: the stocks (Paldy), the violin, the Spanish boot, trial by fire, the pulley, the Dereš bench, the water test, Strapado, and breaking on the wheel."},
        "sk": {"title": "Mučiareň", "short_description": "Stredoveká justícia a metódy vypočúvania", "description": "Mučiareň bola v minulosti neoddeliteľnou súčasťou súdneho systému — úplne normálny a legálny spôsob získavania svedectva alebo priznania. Bežne sa stávalo, že väzeň sa tak vyľakal už len pri pohľade na nástroje, že sa radšej priznal dobrovoľne. Mučenie mohlo trvať rôzne dlho a bolo veľmi účinnou metódou, ktorá takmer vždy vyústila do priznania. Nielen mučenie, ale aj samotný pobyt vo väzení bol utrpením — tmavá, studená, vlhká pivnica bez denného svetla, väzeň často pripútaný priamo k skale. Mučiace nástroje: paldy, husle, španielska čižma, skúška ohňom, kladka, dereš, vodný test, strapado a zlomenie kolesá."},
        "de": {"title": "Folterkammer", "short_description": "Mittelalterliche Justiz und Verhörmethoden", "description": "Die Folterkammer war ein integraler Bestandteil des Justizsystems — eine völlig normale und legale Methode, Geständnisse zu erlangen. Oft gestand ein Gefangener schon beim Anblick der Instrumente freiwillig. Die Folter war sehr effektiv und führte fast immer zum Geständnis. Nicht nur die Folter, sondern auch der Gefängnisaufenthalt war Leiden — dunkler, kalter, feuchter Keller ohne Tageslicht, Gefangene oft an Felsen gekettet. Folterinstrumente: Pfahl, Violine, Spanische Stiefel, Feuerprobe, Rolle, Dereš, Wasserprobe, Strapado und das Rad."},
        "pl": {"title": "Sala tortur", "short_description": "Średniowieczne sądownictwo i metody przesłuchań", "description": "Sala tortur była integralną częścią systemu sądowniczego — całkowicie normalną i legalną metodą uzyskiwania zeznań. Często więzień, widząc tylko instrumenty, przyznawał się dobrowolnie. Tortury były bardzo skuteczne, prawie zawsze kończąc się przyznaniem. Pobyt w więzieniu też był cierpieniem — ciemna, zimna, wilgotna piwnica bez światła, więzień przykuty do skały. Narzędzia: paldy, skrzypce, but hiszpański, próba ognia, bloczek, dereš, próba wodna, strapado i koło."},
        "hu": {"title": "Kínzókamra", "short_description": "Középkori igazságszolgáltatás és kihallgatási módszerek", "description": "A kínzókamra az igazságszolgáltatás szerves része volt — teljesen normális és legális módszer a vallomás megszerzésére. A fogoly már az eszközök láttán is önként vallott. A kínzás szinte mindig vallomással végződött. Nemcsak a kínzás, hanem a börtönbüntetés is szenvedés volt — sötét, hideg, nyirkos pince fény nélkül, a fogoly sziklához láncolva. Kínzóeszközök: palda, hegedű, spanyolcsizma, tűzpróba, csiga, dereš, vízpróba, strapado és a kerék."},
        "fr": {"title": "Chambre de torture", "short_description": "Justice médiévale et méthodes d'interrogatoire", "description": "La chambre de torture faisait partie intégrante du système judiciaire — une méthode tout à fait normale et légale. Un prisonnier confessait souvent volontairement rien qu'à la vue des instruments. La torture aboutissait presque toujours à un aveu. Le séjour en prison aussi était une souffrance — sombre, froide, humide sans lumière, prisonnier enchaîné à la roche. Instruments: stocks, violon, botte espagnole, épreuve du feu, poulie, dereš, épreuve de l'eau, strapado et la roue."},
        "es": {"title": "Cámara de tortura", "short_description": "Justicia medieval y métodos de interrogatorio", "description": "La cámara de tortura era parte integral del sistema judicial — un método completamente normal y legal. Un prisionero a menudo confesaba voluntariamente solo al ver los instrumentos. La tortura casi siempre resultaba en confesión. La estancia en prisión también era sufrimiento — oscuro, frío, húmedo sótano sin luz, prisionero encadenado a la roca. Instrumentos: el paladín, violín, bota española, prueba del fuego, polea, dereš, prueba del agua, strapado y la rueda."},
        "ru": {"title": "Пыточная камера", "short_description": "Средневековое правосудие и методы допроса", "description": "Пыточная камера была неотъемлемой частью судебной системы — совершенно нормальный и законный способ получения признания. Заключённый часто признавался добровольно уже при виде инструментов. Пытки почти всегда приводили к признанию. Само заключение тоже было мучением — тёмный, холодный, сырой подвал без света, заключённый прикован к скале. Орудия: колодки, скрипка, испанский сапог, испытание огнём, блок, дереш, водное испытание, стрападо и колесо."},
        "zh": {"title": "酷刑室", "short_description": "中世纪司法和审讯方法", "description": "酷刑室是司法体系不可分割的一部分——完全正常合法的方式获取认罪。囚犯仅见到刑具就常常自愿认罪。酷刑几乎总是以认罪告终。监禁本身也是痛苦——黑暗、寒冷、潮湿的地下室，囚犯被锁链在岩石上。酷刑工具：枷锁、小提琴、西班牙靴、火刑、滑轮、德雷什、水刑、绞刑架和轮刑。"},
    },
    10: {
        "en": {"title": "In the Zápoľský Palace", "short_description": "The kitchen of the late Gothic Zápoľský palaces", "description": "You passed through the second Romanesque gate, past the remains of a bastion and the beautifully renovated captain's house, and found yourself in front of the Turzovo gate. You are most likely standing in the kitchen of the original western Zápoľský palaces in the Renaissance style — the only room without windows, which served as a passage between rooms. If you look below before entering the tower, you will see the remains of the first building from the 12th century — a large circular stone tower built by the Árpád dynasty, 4 meters in diameter and 23 meters high. Due to tectonic shifts, the tower collapsed. Only after its fall did they begin to build the first castle wall around the entire acropolis."},
        "sk": {"title": "V Zápoľskom paláci", "short_description": "Kuchyňa neskorogotických Zápoľských palácov", "description": "Prešli ste druhou románskou bránou, okolo zvyškov bašty a krásne zrekonštruovaného kapitánskeho domu, a ocitli ste sa pred Turzovskou bránou. S najväčšou pravdepodobnosťou stojíte v kuchyni pôvodných západných zápoľských palácov v renesančnom slohu — jediná miestnosť bez okien, ktorá slúžila ako priechod medzi miestnosťami. Ak sa pred vstupom do veže pozriete dole, uvidíte zvyšky prvej stavby z 12. storočia — rozsiahla kruhová kamenná veža postavená dynastiou Árpádovcov, s priemerom 4 metre a výškou 23 metrov. Kvôli tektonickým posunom veža padla. Až po jej páde začali stavať prvý hradný múr okolo celej akropoly."},
        "de": {"title": "Im Zápoľský-Palast", "short_description": "Die Küche der spätgotischen Zápoľský-Paläste", "description": "Sie sind durch das zweite romanische Tor gegangen, am schön renovierten Kapitänshaus vorbei und stehen vor dem Turzovo-Tor. Sie befinden sich höchstwahrscheinlich in der Küche der Zápoľský-Paläste — der einzige Raum ohne Fenster, der als Durchgang diente. Wenn Sie vor dem Turm nach unten schauen, sehen Sie Reste des ersten Gebäudes aus dem 12. Jahrhundert — ein runder Steinturm der Árpáden, 4 Meter Durchmesser, 23 Meter hoch. Er fiel durch tektonische Verschiebungen. Danach erst begann der Bau der ersten Burgmauer."},
        "pl": {"title": "W Pałacu Zápoľskich", "short_description": "Kuchnia późnogotyckich pałaców Zápoľskich", "description": "Przeszliście przez drugą romańską bramę, minęliście pięknie odrestaurowany dom kapitana i znaleźliście się przed bramą Turzową. Najprawdopodobniej stoicie w kuchni pałaców Zápoľskich — jedyne pomieszczenie bez okien, służące jako przejście. Jeśli spojrzycie w dół przed wieżą, zobaczycie pozostałości pierwszego budynku z XII wieku — okrągła kamienna wieża Arpadów, 4 metry średnicy, 23 metry wysoka. Upadła przez przesunięcia tektoniczne. Dopiero po tym zaczęto budować pierwszy mur zamkowy."},
        "hu": {"title": "A Zápoľský-palotában", "short_description": "A késő gótikus Zápoľský-paloták konyhája", "description": "A második román kapun, a szépen felújított kapitányi házon át jutott a Turzó-kapuhoz. Valószínűleg a Zápoľský-paloták konyhájában áll — az egyetlen ablaktalan helyiség, amely átjáróként szolgált. Ha a torony előtt lenéz, láthatja a 12. századi első épület maradványait — az Árpádok kerek kőtornya, 4 méter átmérővel, 23 méter magasságban. Tektonikus eltolódások miatt összeomlott. Csak ezután kezdték el az első várfal építését."},
        "fr": {"title": "Dans le palais Zápoľský", "short_description": "La cuisine des palais gothiques tardifs des Zápoľský", "description": "Vous êtes passé par la deuxième porte romane, devant la maison du capitaine magnifiquement rénovée, et vous vous trouvez devant la porte Turzovo. Vous êtes très probablement dans la cuisine des palais Zápoľský — la seule pièce sans fenêtre servant de passage. Si vous regardez en bas avant la tour, vous verrez les restes du premier bâtiment du XIIe siècle — une tour ronde en pierre des Árpád, 4 mètres de diamètre, 23 mètres de haut. Elle est tombée par mouvements tectoniques. C'est après qu'on a construit le premier mur."},
        "es": {"title": "En el Palacio Zápoľský", "short_description": "La cocina de los palacios góticos tardíos de los Zápoľský", "description": "Pasó por la segunda puerta románica, junto a la casa del capitán bellamente renovada, y se encontró ante la puerta Turzovo. Probablemente está en la cocina de los palacios Zápoľský — la única habitación sin ventanas que servía de pasaje. Si mira abajo antes de la torre, verá los restos del primer edificio del siglo XII — una torre redonda de piedra de los Árpád, 4 metros de diámetro, 23 metros de alto. Cayó por movimientos tectónicos. Solo después se construyó el primer muro."},
        "ru": {"title": "Во дворце Запольских", "short_description": "Кухня позднеготических дворцов Запольских", "description": "Вы прошли через вторые романские ворота, мимо красиво отреставрированного дома капитана и оказались перед Турзовскими воротами. Скорее всего, вы находитесь на кухне дворцов Запольских — единственная комната без окон, служившая переходом. Если посмотреть вниз перед башней, видны остатки первого здания XII века — круглая каменная башня Арпадов, 4 метра в диаметре, 23 метра высотой. Рухнула из-за тектонических сдвигов. Только после этого началось строительство первой замковой стены."},
        "zh": {"title": "在扎波尔斯基宫殿", "short_description": "晚期哥特式扎波尔斯基宫殿的厨房", "description": "您穿过第二道罗马式大门，经过美丽修缮的队长之家，来到图尔佐沃大门前。您很可能站在扎波尔斯基宫殿的厨房里——唯一没有窗户的房间，用作过道。如果在进入塔楼前向下看，您会看到12世纪第一座建筑的遗迹——阿尔帕德王朝的圆形石塔，直径4米，高23米。因地面构造运动而倒塌。只有在其倒塌之后，才开始建造第一道城墙。"},
    },
    11: {
        "en": {"title": "The Tower — Nebojsa", "short_description": "The last refuge of the castle defenders", "description": "The current 19-meter castle tower was built in the middle of the already fortified acropolis instead of the old one, together with the palace. It served only as a place of last defense and was called Nebojsa. Built by Duke Koloman, son of King Andrew II. The tower had 5 floors including the basement for storing weapons and food. Access was only by wooden ladder to the first floor. The narrow clockwise staircase turns counter-clockwise at the end — this prevented enemies from holding a sword in their right hand. A medieval toilet from the 13th century is preserved in the tower, and on the south side are remains of a sundial. A cistern carved into the rock collected rainwater — the only source of water in the castle."},
        "sk": {"title": "Veža — Nebojsa", "short_description": "Posledné útočisko obrancov hradu", "description": "Súčasná 19-metrová hradná veža bola postavená uprostred už opevnenej akropoly namiesto starej, spolu s palácom. Slúžila len ako miesto poslednej obrany a nazývala sa Nebojsa. Postavil ju vojvoda Koloman, syn kráľa Ondreja II. Veža mala 5 poschodí vrátane suterénu na skladovanie zbraní a potravín. Prístup len po drevenom rebríku na prvé poschodie. Úzke schodisko v smere hodinových ručičiek sa na konci mení na protismerné — to bránilo nepriateľom držať meč v pravej ruke. Vo veži sa zachovala stredoveká toaleta z 13. storočia a na južnej strane zvyšky slnečných hodín. Cisterna vysekaná do skaly zbierala dažďovú vodu — jediný zdroj vody na hrade."},
        "de": {"title": "Der Turm — Nebojsa", "short_description": "Die letzte Zuflucht der Burgverteidiger", "description": "Der heutige 19-Meter-Turm wurde in der Mitte der befestigten Akropolis anstelle des alten errichtet. Er diente als letzter Verteidigungsort und wurde Nebojsa genannt. Gebaut von Herzog Koloman, Sohn von König Andreas II. Der Turm hatte 5 Stockwerke mit Keller für Waffen und Vorräte. Zugang nur per Holzleiter bis zum ersten Stock. Das schmale Treppenhaus dreht sich am Ende gegen den Uhrzeigersinn — das verhinderte Schwertführung. Im Turm ein mittelalterliches WC aus dem 13. Jahrhundert und Sonnenuhr-Reste. Eine Felsenzisterne sammelte Regenwasser."},
        "pl": {"title": "Wieża — Nebojsa", "short_description": "Ostatnie schronienie obrońców zamku", "description": "Obecna 19-metrowa wieża została zbudowana pośrodku ufortyfikowanego akropolu zamiast starej. Służyła jako ostatnie miejsce obrony i nazywała się Nebojsa. Zbudował ją książę Koloman, syn króla Andrzeja II. Wieża miała 5 kondygnacji z piwnicą na broń i żywność. Dostęp tylko po drewnianej drabinie. Wąskie schody zmieniają kierunek na końcu — to uniemożliwiało trzymanie miecza. W wieży zachowała się toaleta z XIII wieku i resztki zegara słonecznego. Cysterna w skale zbierała deszczówkę."},
        "hu": {"title": "A torony — Nebojsa", "short_description": "A vár védőinek utolsó menedéke", "description": "A jelenlegi 19 méteres torony a megerősített akropolisz közepén épült a régi helyett. Csak az utolsó védelmi helyként szolgált és Nebojsának hívták. II. András király fia, Kálmán herceg építtette. A toronynak 5 emelete volt pincével fegyvereknek és élelemnek. Hozzáférés csak falétrán. A szűk lépcső iránya az óramutató járásával ellentétesen változik a végén — ez megakadályozta a kardtartást. A toronyban 13. századi toalett és napóra-maradványok. A sziklaciszterna esővizet gyűjtött."},
        "fr": {"title": "La tour — Nebojsa", "short_description": "Le dernier refuge des défenseurs", "description": "La tour actuelle de 19 mètres a été construite au centre de l'acropole fortifiée à la place de l'ancienne. Elle servait de dernier lieu de défense et s'appelait Nebojsa. Construite par le duc Koloman, fils du roi André II. La tour avait 5 étages avec cave pour armes et vivres. Accès seulement par échelle en bois. L'escalier étroit tourne dans le sens antihoraire à la fin — empêchant de tenir une épée. Dans la tour, toilettes médiévales du XIIIe siècle et restes de cadran solaire. Une citerne dans le roc recueillait l'eau de pluie."},
        "es": {"title": "La torre — Nebojsa", "short_description": "El último refugio de los defensores", "description": "La torre actual de 19 metros se construyó en el centro de la acrópolis en lugar de la antigua. Servía como último bastión de defensa y se llamaba Nebojsa. Construida por el duque Koloman, hijo del rey Andrés II. La torre tenía 5 plantas con sótano para armas y provisiones. Acceso solo por escalera de madera. La escalera gira en sentido contrario al final — impedía sostener la espada. En la torre, retrete medieval del siglo XIII y restos de reloj de sol. Una cisterna en la roca recogía agua de lluvia."},
        "ru": {"title": "Башня — Небойша", "short_description": "Последнее убежище защитников замка", "description": "Нынешняя 19-метровая башня построена в центре укреплённого акрополя вместо старой. Служила последним местом обороны и называлась Небойша. Построена герцогом Коломаном, сыном короля Андраша II. Башня имела 5 этажей с подвалом для оружия и продовольствия. Доступ только по деревянной лестнице. Узкая лестница меняет направление в конце — это мешало держать меч. В башне средневековый туалет XIII века и остатки солнечных часов. Высеченная в скале цистерна собирала дождевую воду."},
        "zh": {"title": "塔楼——内博亚萨", "short_description": "城堡守卫者的最后避难所", "description": "现在的19米高塔楼建在已设防的卫城中央，取代了旧塔楼。仅作为最后防御地点，称为Nebojsa。由安德烈二世之子科洛曼公爵建造。塔楼有5层，地下室存放武器和食物。只能通过木梯进入一楼。狭窄楼梯末端变为逆时针方向——这阻止了持剑。塔楼中保存着13世纪的中世纪厕所和日晷遗迹。凿入岩石的蓄水池收集雨水。"},
    },
    12: {
        "en": {"title": "Romanesque Palace", "short_description": "One of only 4 secular Romanesque palaces preserved in the world", "description": "This arcaded corridor is the only entrance to the late Gothic chapel of St. Elizabeth of Hungary and serves as a museum of weapons and armor. At the back of the rocky plateau stands a massive three-story Romanesque palace — one of only 4 preserved secular Romanesque palaces in the world. Another is in Merano, Italy, where Queen Gertrude, mother of Prince Koloman, also came from. The palace was built as far as possible from the castle gate, on the most inaccessible part of the hill. The Spišský Špan — the royal administrator of Spiš — lived here with his family. On the first floor is one large hall divided by two rows of columns, lit by seven typical Romanesque windows. The palace underwent many structural modifications, but none changed its original Romanesque character."},
        "sk": {"title": "Románsky palác", "short_description": "Jeden zo 4 svetských románskych palácov zachovaných na svete", "description": "Táto arkádová chodba je jediným vstupom do neskorogotickej kaplnky sv. Alžbety Uhorskej a slúži ako múzeum zbraní a brnení. V zadnej časti skalnatej plošiny stojí mohutný trojposchodový románsky palác — jeden zo 4 zachovaných svetských románskych palácov na svete. Ďalší je v talianskom Merane, odkiaľ pochádzala aj kráľovná Gertrúda, matka kniežaťa Kolomana. Palác bol postavený čo najďalej od hradnej brány, na najneprístupnejšej časti kopca. Spišský Špan — kráľovský správca Spiša — žil tu so svojou rodinou. Na prvom poschodí sa nachádza jedna veľká sála rozdelená dvoma radmi stĺpov, osvetlená siedmimi typickými románskymi oknami. Palác prešiel mnohými stavebnými úpravami, ale žiadna nezmenila jeho pôvodný románsky charakter."},
        "de": {"title": "Romanischer Palast", "short_description": "Einer von nur 4 weltlichen romanischen Palästen der Welt", "description": "Dieser Arkadengang ist der einzige Eingang zur spätgotischen Kapelle der Hl. Elisabeth und dient als Waffen- und Rüstungsmuseum. Am hinteren Teil des Felsplateaus steht ein massiver dreigeschossiger romanischer Palast — einer von nur 4 erhaltenen weltlichen romanischen Palästen weltweit. Ein weiterer befindet sich in Merano, Italien. Der Palast wurde am weitesten von der Burgtor entfernt gebaut. Der Spišský Špan — der königliche Verwalter — lebte hier mit seiner Familie. Im ersten Stock ein großer Saal, durch zwei Säulenreihen geteilt, durch sieben romanische Fenster beleuchtet."},
        "pl": {"title": "Pałac romański", "short_description": "Jeden z zaledwie 4 świeckich pałaców romańskich zachowanych na świecie", "description": "Ten arkadowy korytarz jest jedynym wejściem do późnogotyckiej kaplicy św. Elżbiety Węgierskiej i muzeum broni i zbroi. W tylnej części płaskowyżu stoi masywny trzypiętrowy pałac romański — jeden z zaledwie 4 zachowanych świeckich pałaców romańskich na świecie. Kolejny jest w Merano we Włoszech. Pałac zbudowano jak najdalej od bramy zamkowej. Spišský Špan — królewski administrator — mieszkał tu z rodziną. Na pierwszym piętrze wielka sala podzielona dwoma rzędami kolumn, oświetlona siedmioma oknami."},
        "hu": {"title": "Román stílusú palota", "short_description": "A világon megőrzött mindössze 4 világi román palota egyike", "description": "Ez az árkádos folyosó a késő gótikus Szent Erzsébet-kápolna egyetlen bejárata és fegyver- és páncélmúzeum. A sziklás fennsík hátsó részén masszív háromszintes román palota áll — a világon megőrzött mindössze 4 világi román palota egyike. Egy másik az olaszországi Meranóban van. A palotát a várkutól a lehető legtávolabb építették. A Szepesi Špan — a királyi igazgató — itt élt a családjával. Az első emeleten nagy terem, két oszlopsorral osztva, hét román ablakkal megvilágítva."},
        "fr": {"title": "Palais roman", "short_description": "L'un des seulement 4 palais romans séculiers préservés dans le monde", "description": "Ce couloir arcadé est l'unique entrée de la chapelle gothique tardive de Sainte-Élisabeth et musée d'armes et d'armures. À l'arrière du plateau rocheux, un massif palais roman à trois étages — l'un des seulement 4 palais romans séculiers préservés au monde. Un autre se trouve à Merano, Italie. Le palais fut construit aussi loin que possible de la porte. Le Spišský Špan — administrateur royal — vivait ici avec sa famille. Au premier étage, grande salle divisée par deux rangées de colonnes, éclairée par sept fenêtres romanes."},
        "es": {"title": "Palacio románico", "short_description": "Uno de solo 4 palacios románicos seculares preservados en el mundo", "description": "Este corredor de arcos es la única entrada a la capilla gótica tardía de Santa Isabel de Hungría y museo de armas y armaduras. En la parte posterior de la meseta rocosa, un macizo palacio románico de tres plantas — uno de solo 4 palacios románicos seculares conservados en el mundo. Otro está en Merano, Italia. El palacio fue construido lo más lejos posible de la puerta. El Spišský Špan — administrador real — vivía aquí con su familia. En el primer piso, gran sala dividida por dos filas de columnas, iluminada por siete ventanas románicas."},
        "ru": {"title": "Романский дворец", "short_description": "Один из всего 4 светских романских дворцов, сохранившихся в мире", "description": "Этот аркадный коридор — единственный вход в позднеготическую часовню Святой Елизаветы Венгерской и музей оружия и доспехов. В задней части скалистого плато стоит массивный трёхэтажный романский дворец — один из всего 4 сохранившихся в мире светских романских дворцов. Другой находится в Мерано, Италия. Дворец построен как можно дальше от ворот. Спишский Шпан — королевский управляющий — жил здесь с семьёй. На первом этаже большой зал, разделённый двумя рядами колонн, освещённый семью романскими окнами."},
        "zh": {"title": "罗马式宫殿", "short_description": "世界上仅存4座世俗罗马式宫殿之一", "description": "这条拱廊走廊是匈牙利圣伊丽莎白晚期哥特式礼拜堂的唯一入口，也是武器和盔甲博物馆。在岩石高原后部矗立着宏伟的三层罗马式宫殿——世界上仅存4座世俗性罗马式宫殿之一。另一座在意大利梅拉诺。宫殿建在距城堡大门尽可能远的地方。斯皮什行政官——皇家管理员——与家人居住在这里。一楼有一个大厅，仅由两排柱子分隔，被七个典型的罗马式窗户照亮。"},
    },
    13: {
        "en": {"title": "View from the Acropolis", "short_description": "The highest point and panoramic view of the castle", "description": "You have reached the highest point of Spiš Castle — the castle acropolis. From here you have a breathtaking panoramic view of the entire castle complex below you, the surrounding landscape, and the Spiš region. This is where the story of Spiš Castle began in the 12th century. The castle's strategic position on the travertine rock at 634 meters above sea level allowed it to control the entire region for centuries. You can see the entire layout of the castle courtyards, the defensive walls, and towers that we have visited during this tour. Take a moment to appreciate the remarkable achievement of the medieval builders who constructed this magnificent fortress that has stood for over 850 years."},
        "sk": {"title": "Výhľad z akropoly", "short_description": "Najvyšší bod a panoramatický výhľad na hrad", "description": "Dostali ste sa na najvyšší bod Spišského hradu — hradnú akropolu. Odtiaľto máte úchvatný panoramatický výhľad na celý hradný komplex pod vami, okolitú krajinu a región Spiš. Práve tu sa začal príbeh Spišského hradu v 12. storočí. Strategická poloha hradu na travertínovej skale vo výške 634 metrov nad morom mu umožňovala kontrolovať celý región po stáročia. Môžete vidieť celé rozloženie hradných nádvorí, obranných múrov a veží, ktoré sme počas tejto prehliadky navštívili. Zastavte sa a docente pozoruhodný výkon stredovekých staviteľov, ktorí postavili túto nádhernú pevnosť, stojiacu už viac ako 850 rokov."},
        "de": {"title": "Ausblick von der Akropolis", "short_description": "Der höchste Punkt und Panoramablick auf die Burg", "description": "Sie haben den höchsten Punkt der Zipser Burg erreicht — die Burgakropolis. Von hier aus haben Sie einen atemberaubenden Panoramablick auf den gesamten Burgkomplex, die umliegende Landschaft und die Region Zips. Hier begann die Geschichte der Zipser Burg im 12. Jahrhundert. Die strategische Lage auf dem Travertinfelsen in 634 Metern Höhe ermöglichte die Kontrolle der gesamten Region über Jahrhunderte. Sie können das gesamte Layout der Burghöfe, Verteidigungsmauern und Türme sehen, die wir während dieser Tour besucht haben."},
        "pl": {"title": "Widok z akropolu", "short_description": "Najwyższy punkt i panoramiczny widok na zamek", "description": "Dotarliście do najwyższego punktu Zamku Spiskiego — akropolu zamkowego. Stąd roztacza się zapierający dech panoramiczny widok na cały kompleks zamkowy, otaczający krajobraz i region Spiszu. Tu zaczęła się historia Zamku Spiskiego w XII wieku. Strategiczne położenie na trawertynowej skale na 634 m pozwalało kontrolować cały region przez stulecia. Możecie zobaczyć cały układ dziedzińców, murów obronnych i wież odwiedzonych podczas wycieczki."},
        "hu": {"title": "Kilátás az akropoliszról", "short_description": "A legmagasabb pont és panorámás kilátás a várra", "description": "Elérte a Szepesi vár legmagasabb pontját — a várakropoliszt. Innen lélegzetelállító panorámás kilátás nyílik az egész várkomplexumra, a körülötte lévő tájra és a Szepesség vidékére. Itt kezdődött a Szepesi vár története a 12. században. A 634 méteres travertinszikla stratégiai helyzete évszázadokon át lehetővé tette az egész régió ellenőrzését. Látható a várudvarok, falak és tornyok teljes elrendezése, amelyeket a túra során meglátogattunk."},
        "fr": {"title": "Vue depuis l'acropole", "short_description": "Le point le plus haut et vue panoramique du château", "description": "Vous avez atteint le point le plus haut du château de Spiš — l'acropole. De là, vue panoramique à couper le souffle sur l'ensemble du complexe, le paysage environnant et la région de Spiš. C'est ici que l'histoire a commencé au XIIe siècle. La position stratégique sur le travertin à 634 mètres permettait de contrôler toute la région pendant des siècles. Vous pouvez voir l'ensemble des cours, murs et tours visités pendant cette visite."},
        "es": {"title": "Vista desde la acrópolis", "short_description": "El punto más alto y vista panorámica del castillo", "description": "Ha llegado al punto más alto del Castillo de Spiš — la acrópolis. Desde aquí, impresionante vista panorámica de todo el complejo, el paisaje circundante y la región de Spiš. Aquí comenzó la historia en el siglo XII. La posición estratégica en la roca de travertino a 634 metros permitía controlar toda la región durante siglos. Puede ver toda la disposición de patios, murallas y torres visitados durante esta visita."},
        "ru": {"title": "Вид с акрополя", "short_description": "Самая высокая точка и панорамный вид на замок", "description": "Вы достигли самой высокой точки Спишского Града — замкового акрополя. Отсюда захватывающий дух панорамный вид на весь замковый комплекс, окружающий пейзаж и регион Спиш. Именно здесь история началась в XII веке. Стратегическое положение на травертиновой скале на высоте 634 метров позволяло контролировать весь регион на протяжении столетий. Виден весь план дворов, оборонительных стен и башен, посещённых во время этой экскурсии."},
        "zh": {"title": "从卫城俯瞰", "short_description": "最高点和城堡全景", "description": "您已到达斯皮什城堡的最高点——城堡卫城。从这里，您可以看到整个城堡建筑群、周围景观和斯皮什地区的令人叹为观止的全景。正是在这里，斯皮什城堡的故事在12世纪开始。城堡在海拔634米的石灰华岩石上的战略位置使其能够控制整个地区数个世纪。您可以看到我们在这次参观中游览过的整个城堡庭院、防御城墙和塔楼的布局。"},
    },
}

def update_translations():
    collection = db.tour_stops
    updated = 0
    errors = 0

    for stop_number, langs in TRANSLATIONS.items():
        stop = collection.find_one({"stop_number": stop_number})
        if not stop:
            print(f"  WARNING: Stop {stop_number} not found in DB")
            errors += 1
            continue

        existing = {t['language_code']: t for t in stop.get('translations', [])}

        for lang_code, content in langs.items():
            if lang_code in existing:
                existing[lang_code]['title'] = content['title']
                existing[lang_code]['short_description'] = content['short_description']
                existing[lang_code]['description'] = content['description']
            else:
                existing[lang_code] = {
                    'language_code': lang_code,
                    'title': content['title'],
                    'short_description': content['short_description'],
                    'description': content['description'],
                    'audio_url': None,
                    'video_url': None,
                    'vr_url': None,
                }

        result = collection.update_one(
            {"stop_number": stop_number},
            {"$set": {"translations": list(existing.values())}}
        )

        if result.modified_count > 0:
            print(f"  OK: Stop {stop_number} updated ({len(langs)} languages)")
            updated += 1
        else:
            print(f"  INFO: Stop {stop_number} - no changes")

    print(f"\nDone! Updated: {updated}, Errors: {errors}")
    client.close()

if __name__ == "__main__":
    print("Updating Spis Castle tour stop translations...")
    print(f"DB: {DB_NAME}")
    print(f"Stops to update: {len(TRANSLATIONS)}\n")
    update_translations()
